### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by angelkbrown** [Code-the-Dream-School/ee-prac-team2-front#19]
- Make the backend url an environment variable that reads from `.env.development.local`
- Deploy `main` branch as a [Static Site](https://dashboard.render.com/static/new) to Render or as a site on Netlify.
- Set an environment variable for the backend url within Render or Netlify

**Comment by anniethewebcoder** [comment]
https://thrpl.netlify.app/

But I don't know env keys though. Would you tell me so I can add it?

**Comment by anniethewebcoder** [comment]
Added env var.
