### ISSUE TITLE
@Utils path error

### ISSUE THREAD

**Issue by Victoria240** [Code-the-Dream-School/ee-prac-team2-front#36]
I've been getting this error in my DataContainer.tsx file -  Unable to resolve path to module '@utils'.eslint

![Image](https://github.com/Code-the-Dream-School/ee-prac-team2-front/assets/66220547/650d3ab7-6913-4cdf-8d0d-2dd1bd8b83b2)

**Comment by dargaCode** [comment]
@Victoria240 you're no longer seeing this error right?

**Comment by dargaCode** [comment]
Please reopen if it comes up again!

**Comment by dargaCode** [comment]
Please reopen if it comes up again!

**Comment by dargaCode** [comment]
Please reopen if it comes up again!
