### ISSUE TITLE
Create Group page

### ISSUE THREAD

**Issue by Victoria240** [Code-the-Dream-School/ee-prac-team2-front#42]
As a member, I want to create a new group so that I can organize and engage in activities with friends and family.

**User journey**

- The user logs into the application and lands on their dashboard or home page.

- The user notices that they currently do not belong to any group.

- The user decides to create a new group to engage with others.

- The user clicks on a "Create Group" button or a similar CTA (Call to Action) on their dashboard.

- The application navigates the user to a dedicated "Create Group" page or modal.

- The user sees a form with fields to input information about the new group.

Fields may include:
Group Name
Description
Category
Any other relevant details

- The user fills in the required information for the new group.

- The user submits the form by clicking a "Create Group" or "Submit" button.

- The application sends a request to the backend API with the provided group information.

**Outcome** 

1. If the group creation is successful:

The user receives a confirmation message.
The application may automatically redirect the user to the newly created group page or provide a link to it.

2. If there are errors during the group creation process (e.g., validation errors, server errors): 

The user should receive appropriate feedback and guidance.

**Comment by dargaCode** [comment]
edit: removed

**Comment by catbus00** [comment]
Could this also be updated to link to the schema related to https://github.com/Code-the-Dream-School/ee-prac-team2-front/issues/46 ? I am quite lost with how the flow is.
